EntityPersistenceConfig {
 Rule PrefabPersistenceConfigRule "{2742275DBA1245D1B95A342C6BB0033B}" {
  Prefabs {
   "{B1429602172906BC}Prefabs/Props/Civilian/StorageBox.et"
  }
 }
 EntitySerializer GenericEntitySerializer "{BEC5A42CA04C40AE811A05B08AB17DF7}" {
  TransformMask 0x4 0
  ForcePrefab 1
  SaveParent 1
  SavePrefabChildren 1
 }
 ComponentSerializers {
  BaseInventoryStorageComponentSerializer "{2E257315BD0146BE9697D822F77C59F5}" {
   KeepUntrackedItems 1
  }
 ARGH_UniversalInventoryStorageSerializer "{B142A7F8C7BD4E03999FFCA50867748E}" {
 }
 InventoryStorageManagerComponentSerializer "{5FEF3F0F2E9A4B5A}" {
 }
 SCR_DamageManagerComponentSerializer "{419F1471294B40FB87EAE6419F96AEB3}" {
 }
  BLD_DamageManagerComponentSerializer "{69512683FD8242178A5679785D7FFAB1}" {
  }
 ARGH_EditableEntityDamageSerializer "{535A3C8DB6434C3BAA8A8FC846D431DF}" {
 }
 ARGH_BLD_OwnershipComponentSerializer "{6F6C1E1A7F7E4C2FAF7B9B9C4D3E8A11}" {
 }
 }
}
