EntityPersistenceConfig {
 Rule PrefabPersistenceConfigRule "{D9A2C0E6B4C7410A}" {
  Prefabs {
   "{2BF070D6B6BD7558}Prefabs/BaseBuilding/Storage/Safe/Base_Safe.et"
  }
 }
 EntitySerializer GenericEntitySerializer "{D9A2C0E6B4C7410B}" {
 }
 ComponentSerializers {
  BLD_OwnershipComponentSerializer "{60CDA06262D6446889B952A7BBE5D8B9}" {
  }
  BaseInventoryStorageComponentSerializer "{D9A2C0E6B4C7410C}" {
   KeepUntrackedItems 1
  }
  ARGH_UniversalInventoryStorageSerializer "{3F64DF312D02419DA1D2BAC6293A3B96}" {
  }
  InventoryStorageManagerComponentSerializer "{D9A2C0E6B4C7410D}" {
  }
  SCR_DamageManagerComponentSerializer "{D9A2C0E6B4C7410E}" {
  }
  BLD_DamageManagerComponentSerializer "{BF423E0AD5964BA3B1B5E69A5F3CF289}" {
  }
  ARGH_EditableEntityDamageSerializer "{AE9F424225D94E2BAD26E2585A607909}" {
  }
  ARGH_BLD_OwnershipComponentSerializer "{8E7E8B1F2A7C4D38BEEAD5C9F25A7C3E}" {
  }
 }
}
