EntityPersistenceConfig {
 Rule PrefabPersistenceConfigRule "{D9A2C0E6B4C7410A}" {
  Prefabs {
   "{2BF070D6B6BD7558}Prefabs/BaseBuilding/Storage/Safe/Base_Safe.et"
  }
 }
 EntitySerializer GenericEntitySerializer "{D9A2C0E6B4C7410B}" {
  TransformMask 0x4 0
  ForcePrefab 1
  SaveParent 1
  SavePrefabChildren 1
 }
 ComponentSerializers {
  BLD_OwnershipComponentSerializer "{89B952A7BBE5D8B9}" {
  }
  BaseInventoryStorageComponentSerializer "{D9A2C0E6B4C7410C}" {
   KeepUntrackedItems 1
   ForceSlotIndices 1
   ForceSlotId 1
  }
  ARGH_UniversalInventoryStorageSerializer "{A1D2BAC6293A3B96}" {
  }
  InventoryStorageManagerComponentSerializer "{D9A2C0E6B4C7410D}" {
  }
  SCR_DamageManagerComponentSerializer "{D9A2C0E6B4C7410E}" {
  }
  BLD_DamageManagerComponentSerializer "{B1B5E69A5F3CF289}" {
  }
  ARGH_EditableEntityDamageSerializer "{AD26E2585A607909}" {
  }
  ARGH_BLD_OwnershipComponentSerializer "{BEEAD5C9F25A7C3E}" {
  }
 }
}