EntityPersistenceConfig {
 Rule PrefabPersistenceConfigRule "{B95A342C6BB0033B}" {
  Prefabs {
   "{B1429602172906BC}Prefabs/Props/Civilian/StorageBox.et"
  }
 }
 EntitySerializer GenericEntitySerializer "{811A05B08AB17DF7}" {
  TransformMask 0x4 0
  ForcePrefab 1
  SaveParent 1
  SavePrefabChildren 1
 }
 ComponentSerializers {
  BaseInventoryStorageComponentSerializer "{9697D822F77C59F5}" {
   KeepUntrackedItems 1
   ForceSlotIndices 1
   ForceSlotId 1
  }
  ARGH_UniversalInventoryStorageSerializer "{999FFCA50867748E}" {
  }
  InventoryStorageManagerComponentSerializer "{5FEF3F0F2E9A4B5A}" {
  }
  SCR_DamageManagerComponentSerializer "{87EAE6419F96AEB3}" {
  }
  BLD_DamageManagerComponentSerializer "{8A5679785D7FFAB1}" {
  }
  ARGH_EditableEntityDamageSerializer "{AA8A8FC846D431DF}" {
  }
  ARGH_BLD_OwnershipComponentSerializer "{AF7B9B9C4D3E8A11}" {
  }
 }
}