ARGH_RandomSpawnConfig {
 Enabled 1
 AllowedSpawnNames {
  "Kamensk Coast"
  "Ugoldar Coast"
  "Mineraly Coast"
  "Random Coastal"
 }
 AllowedFactionKey "PLAYERS"
 AvoidLastNPerPlayer 2
 FallbackToMenuOnEmptyPool 0
 UseSpawnPointRandomRadius 1
}
