EntityPersistenceConfig {
 Rule PrefabPersistenceConfigRule "{64F09C88C714F0E9}" {
  Prefabs +{
  }
 }
 EntitySerializer GenericEntitySerializer "{64CAFB94FEC83585}" {
  TransformMask 0x4 0
  ForcePrefab 1
  SaveParent 1
  SavePrefabChildren 1
 }
 ComponentSerializers {
  BaseInventoryStorageComponentSerializer "{64CAFB94F9FE31A6}" {
  }
  SCR_DamageManagerComponentSerializer "{B4D2A7C9E16F8B35}" {
  }
 }
}