EntityPersistenceConfig {
 Rule EntityClassPersistenceConfigRule "{6572819621E8D479}" {
  EntityClass "PlayerController"
 }
 SelfDelete 0
 SelfSpawn 0
 EntitySerializer SCR_PlayerControllerSerializer "{6572819A61C589CB}" {
 }
 ComponentSerializers {
  SCR_PlayerFactionAffiliationComponentSerializer "{657281999F5D0F54}" {
  }
  SCR_PlayerXPHandlerComponentSerializer "{65EAB150A92E1A7A}" {
  }
  SCR_FastTravelComponentSerializer "{65EAB158B13312A1}" {
  }
  SCR_PlayerLoadoutComponentSerializer "{663CD1EB63935002}" {
  }
  SCR_PlayerSupplyAllocationComponentSerializer "{66AC979D03BBD12B}" {
  }
  SCR_ResourceComponentSerializer "{76A8EE8EE23F43509FB6D91C6FB0E990}" {
  }
 }
}
