EntityPersistenceConfig {
 Rule PrefabPersistenceConfigRule "{2F75C0A0D0184F9B9A87E3FA4B0A9120}" {
 Prefabs {
   "{334DDCDFBE1A0C7A}Prefabs/Empty.et"
   "{C9C0AA3EE517F690}Prefabs/Props/Door.et"
   "{647142C85E61F83A}Prefabs/BaseBuilding/Garage/GarageDoor.et"
  }
 }
 EntitySerializer GenericEntitySerializer "{E73A86D85A7D4B4FB648D4D2E19B7A83}" {
  TransformMask 0x4 0
  ForcePrefab 1
  SaveParent 1
  SavePrefabChildren 1
 }
 ComponentSerializers {
  ARGH_BLD_OwnershipComponentSerializer "{8E2B14F0A7C44A66B9FC84B376E9CF23}" {
  }
  DoorComponentSerializer "{D2B4A3D2A0C74D8F88DAF8D37E3EC5E2}" {
  }
 }
}
