EntityPersistenceConfig {
 Rule PrefabPersistenceConfigRule "{A7B3A9D9C6D04D21}" {
  Prefabs {
   "{B70CAD8D53F7267C}Prefabs/Props/Ceiling.et"
   "{745A6C8FA5BE01BB}Prefabs/Props/Foundation.et"
   "{F2CAA88E556DF686}Prefabs/Props/WallSmall.et"
   "{74D184088BFF6CEC}Prefabs/Props/Stairs.et"
   "{417ADB670039E3D8}Prefabs/Props/Doorway.et"
   "{21C1293564011BB4}Prefabs/Props/Glass.et"
   "{7420EF868C491C49}Prefabs/Props/StairFoundation.et"
   "{BFEBBF26A643FBA6}Prefabs/Props/Window.et"
   "{134F263C895CE56B}Prefabs/Props/Wall.et"
   "{1BD271718EA3645B}Prefabs/BaseBuilding/SleepingBag/SleepingBag.et"
   "{D1EC02E5F307FCCB}Prefabs/BaseBuilding/SleepingBag/BedManager.et"
   "{609ADC868AD38BDB}Prefabs/BaseBuilding/Flag/Flag.et"
   "{2CF1B53612BB8956}Prefabs/BaseBuilding/Flag/FlagGhost.et"
   "{49CB86DE0B2A2659}Prefabs/Props/Fabric/Flags/Flag_2_3_Everon_01.et"
   "{D4BC29A37012A207}Prefabs/DoorFix.et"
   "{E0188D338D779179}Prefabs/Props/BsBox/BsBoxPlans.et"
   "{4817EBF95F63830D}Prefabs/Props/BsBox/BsBox.et"
  }
 }
 EntitySerializer GenericEntitySerializer "{A7B3A9D9C6D04D22}" {
  TransformMask 0x4 0
  ForcePrefab 1
  SaveParent 1
  SavePrefabChildren 1
 }
 ComponentSerializers {
  SCR_DamageManagerComponentSerializer "{A7B3A9D9C6D04D23}" {
  }
  BLD_DamageManagerComponentSerializer "{D72E754AB628477C8FC71C72D647803E}" {
  }
  ARGH_EditableEntityDamageSerializer "{1852B3A418584BA991A545457B7E8D54}" {
  }
  ARGH_BLD_OwnershipComponentSerializer "{C5C3D7E4D0D746F7A9D3D12B9E6A1F2D}" {
  }
 }
}
