EntityPersistenceConfig {
 Rule PrefabPersistenceConfigRule "{CDE4F6BD4FB9490BB3D56E1AFD32BC8F}" {
  Prefabs {
   "{98772037608AC4D7}Prefabs/Props/Civilian/Nail.et"
   "{344BEBA1D2C8095C}Prefabs/Props/Civilian/Nails.et"
   "{703F2DB693C60ABF}Prefabs/Props/Civilian/NewBasePlans.et"
   "{06F1E252DC029B8C}Prefabs/Props/Civilian/Plank.et"
   "{E0F0EA05247DFCEA}Prefabs/Props/Civilian/Log.et"
   "{173AB5EB5EF99F21}Prefabs/Props/Civilian/StorageBoxPlans.et"
   "{D5D3CC0E5FA82395}Prefabs/Saw/Saw.et"
   "{F6A5E9A099A2FAE7}Prefabs/System/PriceSetter.et"
   "{D125E11C31A965AA}Prefabs/BaseBuilding/Storage/Safe/SafeBook.et"
   "{535141D3EBC36D1E}Prefabs/BaseBuilding/Flag/FlagPlans.et"
   "{E0188D338D779179}Prefabs/Props/BsBox/BsBoxPlans.et"
  }
 }
 EntitySerializer GenericEntitySerializer "{FE3CED9F459A4BD9AA29D34BB36A68A8}" {
  TransformMask 0x4 0
  ForcePrefab 1
  SaveParent 1
  SavePrefabChildren 1
 }
 ComponentSerializers {
  BaseInventoryStorageComponentSerializer "{702890876D314C1F915234DC24E3F338}" {
   KeepUntrackedItems 1
   ForceSlotIndices 1
   ForceSlotId 1
  }
  SCR_DamageManagerComponentSerializer "{1595B6EDB09A44618F1B2E0282AA2A6C}" {
  }
 }
}
