PersistenceSystemConfig : "{5BA7C4643477E2D7}Configs/Systems/Persistence/EditableMission.conf" {
 Databases {
  SaveGameDatabase "{6624ADA9A88DA0F6}" {
   SerializationSaveContext "SCR_PersistencePrettyJsonSaveContext"
   SerializationLoadContext "SCR_PersistenceJsonLoadContext"
   Bundler "JsonBundler"
  }
 }
 Configurations {
  PersistenceConfigGroup Entities {
   Configurations {
    PersistenceConfigGroup Player {
     Configurations {
      EntityPersistenceConfig "{65728196752AB09A}" : "{3CEC5D580421E71E}Configs/Systems/Persistence/Configuration/PlayerController.conf" {
       Collection "{6572819669ACAF54}"
      }
      EntityPersistenceConfig "{64ECE6462993EA13}" : "{FA4B563CF52F6F25}Configs/Systems/Persistence/Configuration/Character/Player.conf" {
       Collection "{64EACAC5B77ED31B}"
      }
     }
    }
    PersistenceConfigGroup Items {
     Configurations {
      EntityPersistenceConfig "{64CAFB94F1A3338C}" : "{59A157EBABAC7AEC}Configs/Systems/Persistence/Configuration/Item.conf" {
       Collection "{64CAFB94EE84A3ED}"
       EntitySerializer GenericEntitySerializer "{64CAFB94FEC83585}" {
        TransformMask 0x4 0
        ForcePrefab 1
        SaveParent 1
        SavePrefabChildren 1
       }
       ComponentSerializers {
        BaseInventoryStorageComponentSerializer "{64CAFB94F9FE31A6}" {
         KeepUntrackedItems 1
         ForceSlotIndices 1
         ForceSlotId 1
        }
        SCR_DamageManagerComponentSerializer "{B4D2A7C9E16F8B35}" {
        }
       }
      }
     EntityPersistenceConfig "{29624146ACDA4828AE128EC0646F23FD}" : "{62C80F86AD0146CD8574BB72459059E0}Configs/Systems/Persistence/Configuration/Item/ARGH_BuildingItems.conf" {
       Collection "{64CAFB94EE84A3ED}"
     }
     EntityPersistenceConfig "{09D85037FFBC4729BEE48DE55590F9CF}" : "{CD6E91E6AC3042C3B97A78B00E980F7B}Configs/Systems/Persistence/Configuration/Item/ARGH_FoodDrinkItems.conf" {
      Collection "{64CAFB94EE84A3ED}"
     }
     EntityPersistenceConfig "{65AEC521005E5B19}" {
      Collection "{64CAFB94EE84A3ED}"
      EntitySerializer GenericEntitySerializer "{65AEC521C27ACD06}" {
       TransformMask 0x4 0
        ForcePrefab 1
        SaveParent 1
        SavePrefabChildren 1
       }
      }
    }
    }
    PersistenceConfigGroup Storages {
     Configurations {
      EntityPersistenceConfig "{657D1167F37759DE}" : "{C9C19583E2FF5B90}Configs/Systems/Persistence/Configuration/Storage/StorageHolder.conf" {
       Collection "{657D11673BFC485D}"
       ComponentSerializers {
        BaseInventoryStorageComponentSerializer "{657D1167CFD50CC5}" {
         KeepUntrackedItems 1
        }
       }
      }
      EntityPersistenceConfig "{667C7CA5A5DD4912}" : "{011C8ED5B2533223}Configs/Systems/Persistence/Configuration/Storage/StorageBox.conf" {
       Collection "{657D11673BFC485D}"
      }
      EntityPersistenceConfig "{D9A2C0E6B4C7411A}" : "{8B0D1C4A6BCE4B11}Configs/Systems/Persistence/Configuration/Storage/ARGH_SafeStorage.conf" {
       Collection "{657D11673BFC485D}"
      }
      EntityPersistenceConfig "{55EC10606D2A4419AC9224047A115348}" : "{3591F7AE19AE467A96E2ECD5B1836CF1}Configs/Systems/Persistence/Configuration/Storage/ARGH_StorageBox.conf" {
       Collection "{657D11673BFC485D}"
      }
     }
    }
   }
  }
 }
 PersistenceConfigGroup ScriptedStates {
  Configurations {
   PersistenceConfigGroup Gameplay {
    Configurations {
     ScriptedStatePersistenceConfig "{26040555C89249EFB6FBDEC8B92E3119}" {
      Collection "{6586D01E488CA578}"
      Serializer DE_EconomySystemSerializer "{311E1B4DC1B7427EA09B63149055E6A9}" {
      }
     }
    }
   }
  }
 }
}
PersistentStates {
 DE_EconomySystemData "{670A002CE403D2A0}" {
 }
}
